name: snappyv310
version: 3.10.0
summary: A generic amd64 kernel built from source
description: This is a generic kernel for amd64 / kvm built using x86_64_defconfig plus the minimal snappy config changes
type: kernel

parts:
  kernel:
    plugin: kernel
    source: .
    source-branch: snappy_v3.10
    source-type: git
    build-packages: [bc]
    kdefconfig: [x86_64_defconfig, snappy/generic.config, snappy/security.config, snappy/systemd.config, snappy/snappy.config, snappy/containers.config]
    kconfigs:
      - CONFIG_LOCALVERSION="-snappy_v3.10"
    kernel-initrd-modules:
      - squashfs
    kernel-initrd-firmware:
      - lib/firmware/e100/d101m_ucode.bin
      - lib/firmware/e100/d101s_ucode.bin
      - lib/firmware/e100/d102e_ucode.bin
    kernel-image-target: bzImage
